'use client';
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { m } from 'framer-motion';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const theme = extendTheme({
  colors: {
    primary: {
      purple: 'hsl(259, 100%, 65%)',
      lightRed: 'hsl(0, 100%, 67%)',
    },
    neutral: {
      white: 'hsl(0, 0%, 100%)',
      offWhite: ' hsl(0, 0%, 94%)',
      lightGrey: 'hsl(0, 0%, 86%)',
      smokeyGrey: 'hsl(0, 1%, 44%)',
      offBlack: 'hsl(0, 0%, 8%)',
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
